# NumPy

<ol>
    <li>NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. </li>
    <li>The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures. </li>
    <li>At the core of the NumPy package, is the ndarray object</li>
    
</ol>

### Python Sequences VS NumPy Arrays
<table border='5'>
    <tr>
        <th>Python Sequences</th>
        <th>NumPy Arrays</th>
    </tr>
    <tr>
        <td>Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.</td>
        <td>NumPy arrays have a fixed size at creation.</td>
    </tr>
    <tr>
        <td>Python list can have different datatypes elements.</td>
        <td>The elements in a NumPy array are all required to be of the same data typeand thus will be the same size in memory.</td>
    </tr>
    <tr>
        <td>Mathematical operations on Python lists usually require loops and more lines of code, making them less efficient for large datasets.</td>
        <td>NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.</td>
    </tr>
    <tr>
        <td>Python lists are supported by many libraries, but they are often converted into NumPy arrays before processing scientific or mathematical data.</td>
        <td>NumPy arrays are widely used in scientific and mathematical Python packages and are the standard data structure for numerical computing.</td>
    </tr>
</table>

### Why NumPy is Fastest

# Vectorization

- Vectorization is the process of performing operations on entire NumPy arrays without using explicit loops or indexing in Python. The operations are executed internally using optimized C code.

- Vectorized code is more concise and easier to read, requiring fewer lines of code compared to traditional looping methods.

- Using fewer lines of code reduces the chances of errors and bugs, making programs more reliable.

- Vectorization makes code resemble standard mathematical notation, making mathematical computations easier to understand and implement.

- It produces more Pythonic and efficient code by avoiding slow and difficult-to-read `for` loops.

# Broadcasting

- Broadcasting is the mechanism that allows NumPy to perform implicit element-by-element operations on arrays.

- Broadcasting applies to arithmetic, logical, bitwise, and functional operations, enabling efficient computation on arrays.

- It works when arrays have the same shape, when one operand is a scalar, or when arrays have compatible shapes.

- If a smaller array can be expanded to match the shape of a larger array without ambiguity, NumPy automatically performs the operation using broadcasting.

## Creating NumPy Arrays

In [2]:
# Importing np.array
import numpy as np

In [5]:
a = np.array([1,2,3]) #1-D
print(a)

[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [8]:
b = np.array([[1,2,3],[3,2,1]]) #2-D
print(b)

[[1 2 3]
 [3 2 1]]


In [24]:
# dtype
# Specifies the data type of elements in a NumPy array.

# Syntax:
# np.array(data, dtype=type)

# Important:
# dtype controls how data is stored in memory.
# All elements in a NumPy array generally have the same dtype.
# Changing dtype can improve memory efficiency or precision.

# Common dtypes:
# int, float, bool, complex

c = np.array([1,2,0,1,-1],dtype=float)
print(c)
c = np.array([1,2,0,1,-1],dtype=bool)
print(c)

[ 1.  2.  0.  1. -1.]
[ True  True False  True  True]


In [23]:
# np.arange()
# Creates a NumPy array with evenly spaced values within a given range.

# Syntax:
# np.arange(start, stop, step)

# Parameters:
# start -> starting value (included)
# stop  -> ending value (excluded)
# step  -> difference between each value

# Important:
# The stop value is NOT included.
# Works similar to Python range() but returns a NumPy array.
# Useful for generating sequences of numbers.

d = np.arange(1,11) # 1 to 10 
print(d)

d = np.arange(2,21,2) # Table of 2
print(d)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [22]:
# reshape()
# Used to change the shape (dimensions) of a NumPy array.
# It does not change the data, only the arrangement of elements.

# Syntax:
# array.reshape(rows, columns)

# Important:
# The total number of elements must remain the same.
# rows × columns = total elements in the array.
# Otherwise, NumPy raises a ValueError.

e = np.arange(1,11).reshape(2,5)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
# np.ones()
# Creates a NumPy array filled with 1s.

# Syntax:
# np.ones(shape, dtype=data_type)

# Parameters:
# shape -> Size of the array (e.g., 5, (2,3), (3,3))
# dtype -> Optional, specifies the data type

# Important:
# By default, elements are of float type (1.0).
# Useful for initializing arrays with all values set to 1.

f = np.ones((2, 3))
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# np.zeros()
# Creates a NumPy array filled with 0s.

# Syntax:
# np.zeros(shape, dtype=data_type)

# Parameters:
# shape -> size of the array (e.g., 5, (2,3), (4,4))
# dtype -> optional, defines the data type

# Important:
# By default, values are float (0.0).
# Used for initializing arrays before computation.

g = np.zeros((4,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
# np.random
# Used to generate random numbers in NumPy.

# Common functions:

# np.random.rand()
# Generates random float numbers between 0 and 1.
# Shape is given as separate arguments
arr1 = np.random.rand(3)
print(arr1)

# np.random.randint(start, stop, size)
# Generates random integers from start to stop (stop excluded).
arr2 = np.random.randint(1, 10, 5)
print(arr2)

# np.random.randn()
# Generates numbers from a normal (Gaussian) distribution.
arr3 = np.random.randn(2, 2)
print(arr3)

# np.random.random()
# Shape is given as a tuple
arr4 = np.random.random((2, 3))
print(arr4)

# Important:
# Useful in simulations, testing, machine learning, and data generation.
# Numbers are pseudo-random (generated using an algorithm, not truly random).

[0.45688562 0.5001771  0.39566947]
[4 6 6 5 8]
[[-0.78639854  1.34679957]
 [ 0.20494823 -1.54956827]]
[[0.36936249 0.32839483 0.78638313]
 [0.12894368 0.62353281 0.30650105]]


In [42]:
# np.linspace()
# Generates evenly spaced numbers over a specified range.

# Syntax:
# np.linspace(start, stop, num)

# Parameters:
# start -> starting value (included)
# stop  -> ending value (included)
# num   -> number of values to generate

# Important:
# Unlike arange(), the stop value IS included.
# It does not use step size; instead it uses number of points.
# Useful for graphs and plotting smooth curves.

h = np.linspace(-10,10,10)
print(h)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [41]:
# np.identity()
# Creates an identity matrix (square matrix with 1s on diagonal and 0s elsewhere).

# Syntax:
# np.identity(n, dtype=float)

# Parameters:
# n -> size of the matrix (n x n)
# dtype -> optional data type (default is float)

# Important:
# Only square matrices are created (rows = columns).
# Diagonal elements are 1, all others are 0.
# Used in linear algebra.

# Example:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array Attributes

In [43]:
a1 = np.arange(10)
print(a1)
a2=np.arange(12,dtype=float).reshape(3,4)
print(a2)
a3=np.arange(8).reshape(2,2,2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [47]:
# ndim
# It tells the number of dimensions (axes) of a NumPy array.
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [51]:
# shape
# It tells the structure of the array in terms of dimensions. 
# i.e size of each dimension
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [56]:
# size
# It tells the total number of elements in a NumPy array.

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [57]:
# itemsize
# It tells the size (in bytes) of one element in the array.
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [58]:
# dtype
# It tells the data type of elements stored in a NumPy array. 
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


## Changing Datatype

In [63]:
# astype()
# Used to change the data type (dtype) of a NumPy array. 

print(a2.dtype)
a2.astype(np.float32)

float64


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

## Array Operations

In [64]:
a1 = np.arange(12).reshape(3,4)
print(a1)
a2 = np.arange(12,24).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Scalar Operations

In [ ]:
# Arithmetic

In [66]:
# addition
print(a1 + 2)

# subtraction
print(a1 - 2)

# multiplication
print(a1 * 3)

# division
print(a1 / 2)

# power
print(a1 ** 2)

# modulus
print(a1 % 2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [67]:
# Relational 

In [68]:
# greater than
print(a1 > 5)

# less than
print(a1 < 5)

# greater than or equal
print(a1 >= 5)

# less than or equal
print(a1 <= 5)

# equal to
print(a1 == a2)

# not equal to
print(a1 != a2)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### Vector Operations

In [69]:
# Arithmetic

In [70]:
# addition (element-wise)
print(a1 + a2)

# subtraction
print(a1 - a2)

# multiplication (element-wise)
print(a1 * a2)

# division
print(a1 / a2)

# floor division
print(a1 // a2)

# modulus
print(a1 % a2)

# power
print(a1 ** 2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


## Arrays Function

In [72]:
import numpy as np

a = np.random.random((3,3))
a = np.round(a1 * 100)

print(a)

[[ 100. 3800. 1800.]
 [1600.  400. 4800.]
 [5100. 9700. 8300.]]


In [73]:
# 1. max / min / sum / prod
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.prod(a))

9700.0
100.0
35600.0
8.62774530048e+29


In [79]:
# axis = 0 => col and 1 => row

# Every row min

print(np.min(a,axis=0))
print(np.max(a,axis=1))

[ 100.  400. 1800.]
[3800. 4800. 9700.]


In [81]:
# 2. mean / median / std / var
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

3955.5555555555557
3800.0
3190.649920248263
10180246.913580246


In [82]:
# 3. trigonometric functions
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[[-0.50636564 -0.97045533  0.13220235]
 [-0.80122479 -0.85091936 -0.34625357]
 [-0.93026087 -0.94516985 -0.08767806]]
[[ 0.86231887  0.24128085 -0.99122275]
 [-0.59836346 -0.52529634  0.93814096]
 [-0.36689877  0.32657918  0.99614886]]
[[-0.58721392 -4.02209838 -0.133373  ]
 [ 1.33902693  1.61988443 -0.3690848 ]
 [ 2.53547011 -2.89415214 -0.08801702]]


In [83]:
# 4. dot product
b = np.arange(9, 18).reshape(3, 3)
print(np.dot(a, b))

[[ 73500.  79200.  84900.]
 [ 91200.  98000. 104800.]
 [286800. 309900. 333000.]]


In [84]:
# 5. log and exponents
print(np.log(a))
print(np.exp(a))
print(np.log10(a))

[[4.60517019 8.24275635 7.49554194]
 [7.37775891 5.99146455 8.4763712 ]
 [8.53699582 9.17988116 9.02401079]]
[[2.68811714e+043             inf             inf]
 [            inf 5.22146969e+173             inf]
 [            inf             inf             inf]]
[[2.         3.5797836  3.25527251]
 [3.20411998 2.60205999 3.68124124]
 [3.70757018 3.98677173 3.91907809]]


C:\Users\Himanshu Kumar Singh\AppData\Local\Temp\ipykernel_17644\2058894067.py:3: RuntimeWarning: overflow encountered in exp
  print(np.exp(a))


In [85]:
# 6. round / floor / ceil
x = np.array([1.2, 2.7, 3.5])
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))

[1. 3. 4.]
[1. 2. 3.]
[2. 3. 4.]


## Indexing and Slicing

In [87]:
a1 = np.arange(10)
print("a1:", a1)

a2 = np.arange(12).reshape(3,4)
print("\na2:\n", a2)

a3 = np.arange(8).reshape(2,2,2)
print("\na3:\n", a3)

a1: [0 1 2 3 4 5 6 7 8 9]

a2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [88]:
# -------------------------
# 1D Array (a1) Indexing & Slicing
# -------------------------
print("\n1D Indexing:")
print(a1[0])      # first element
print(a1[-1])     # last element

print("\n1D Slicing:")
print(a1[2:7])    # from index 2 to 6
print(a1[:5])     # first 5 elements
print(a1[::2])    # step = 2

# -------------------------
# 2D Array (a2) Indexing & Slicing
# -------------------------
print("\n2D Indexing:")
print(a2[0, 0])   # first row first column
print(a2[2, 3])   # last element

print("\n2D Slicing:")
print(a2[0])      # first row
print(a2[:, 1])   # all rows, column 1
print(a2[1:, 2:]) # sub-matrix

# -------------------------
# 3D Array (a3) Indexing & Slicing
# -------------------------
print("\n3D Indexing:")
print(a3[0])        # first 2D block
print(a3[1, 0, 1])  # specific element

print("\n3D Slicing:")
print(a3[:, 1])     # second row of each block
print(a3[:, :, 1])  # second column of all blocks


1D Indexing:
0
9

1D Slicing:
[2 3 4 5 6]
[0 1 2 3 4]
[0 2 4 6 8]

2D Indexing:
0
11

2D Slicing:
[0 1 2 3]
[1 5 9]
[[ 6  7]
 [10 11]]

3D Indexing:
[[0 1]
 [2 3]]
5

3D Slicing:
[[2 3]
 [6 7]]
[[1 3]
 [5 7]]


## Iteration

In [89]:
a1 = np.arange(10)
print("a1:\n", a1)

a2 = np.arange(12).reshape(3,4)
print("\na2:\n", a2)

a3 = np.arange(8).reshape(2,2,2)
print("\na3:\n", a3)

# -------------------------
# Iteration in 1D array
# -------------------------
print("\n1D iteration:")
for i in a1:
    print(i)

# -------------------------
# Iteration in 2D array (row-wise)
# -------------------------
print("\n2D iteration (rows):")
for row in a2:
    print(row)

print("\n2D iteration (element-wise):")
for i in np.nditer(a2):
    print(i)

# -------------------------
# Iteration in 3D array
# -------------------------
print("\n3D iteration (blocks):")
for block in a3:
    print(block)

print("\n3D full iteration (all elements):")
for i in np.nditer(a3):
    print(i)

a1:
 [0 1 2 3 4 5 6 7 8 9]

a2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

1D iteration:
0
1
2
3
4
5
6
7
8
9

2D iteration (rows):
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]

2D iteration (element-wise):
0
1
2
3
4
5
6
7
8
9
10
11

3D iteration (blocks):
[[0 1]
 [2 3]]
[[4 5]
 [6 7]]

3D full iteration (all elements):
0
1
2
3
4
5
6
7


In [90]:
a = np.arange(12).reshape(3,4)
print("Original array:\n", a)

# -------------------------
# 1) reshape()
# -------------------------
# Changes shape without changing data
print("\nReshape (2,6):\n", a.reshape(2,6))

# -------------------------
# 2) transpose()
# -------------------------
# Swaps rows and columns (for 2D arrays)
print("\nTranspose:\n", a.transpose())
# OR
print("\nShortcut transpose:\n", a.T)

# -------------------------
# 3) ravel()
# -------------------------
# Converts multi-D array into 1D array (flatten view)
print("\nRavel:\n", a.ravel())

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshape (2,6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Shortcut transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Ravel:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


## Stacking

In [91]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 2D arrays for better understanding
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

b2 = np.array([[7, 8, 9],
               [10, 11, 12]])

print("a2:\n", a2)
print("b2:\n", b2)

# -------------------------
# 1) Horizontal stacking  : Joins arrays side by side (columns increase)
# -------------------------
print("\nHorizontal stacking (column-wise):")
print(np.hstack((a2, b2)))

# -------------------------
# 2) Vertical stacking  : Joins arrays one above another (rows increase)
# -------------------------
print("\nVertical stacking (row-wise):")
print(np.vstack((a2, b2)))

a2:
 [[1 2 3]
 [4 5 6]]
b2:
 [[ 7  8  9]
 [10 11 12]]

Horizontal stacking (column-wise):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Vertical stacking (row-wise):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Spliting

In [93]:
a = np.arange(12)
print("Original array:\n", a)

# -------------------------
# 1) 1D splitting
# -------------------------
print("\n1D split:")
print(np.split(a, 3))   # split into 3 equal parts

# -------------------------
# 2) 2D array splitting
# -------------------------
a2 = np.arange(12).reshape(3,4)
print("\n2D array:\n", a2)

print("\nHorizontal split (column-wise):")
print(np.hsplit(a2, 2))   # split columns

print("\nVertical split (row-wise):")
print(np.vsplit(a2, 3))   # split rows

# -------------------------
# 3) uneven split (example)
# -------------------------
a3 = np.arange(10)
print("\nEven split:")
print(np.array_split(a3, 3))  # works even if not perfectly divisible

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

1D split:
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Horizontal split (column-wise):
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]

Vertical split (row-wise):
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

Even split:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
