# np.sort

## 1) Name
**np.sort** – NumPy function used to sort the elements of an array.

## 2) Syntax
```python
np.sort(a, axis=-1, kind=None, order=None)
```

## 3) Usage
Sorts array elements in ascending order and returns a new sorted array.

## Note
- Returns a new sorted array.
- Does not modify the original array.

In [2]:
import numpy as np

In [6]:
a = np.random.randint(1,100,25) # 1-D
a

array([50, 80, 67, 55, 45,  4,  6, 87, 47, 81, 85, 77, 11, 81, 12, 63, 26,
       20, 21, 76, 31, 19, 31, 70, 39])

In [5]:
print(np.sort(a))

[ 3  4  7 10 11 13 14 19 22 30 33 37 47 52 58 61 62 64 67 67 73 75 79 86
 88]


In [13]:
b = np.arange(1, 21).reshape(4, 5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
print(np.sort(b)) # row wise sorting

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(np.sort(b , axis = 0 )) # Col wise sorting

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
# Descending Order Sorting
print(np.sort(a)[::-1])

[87 85 81 81 80 77 76 70 67 63 55 50 47 45 39 31 31 26 21 20 19 12 11  6
  4]


# np.append

## 1) Name
**np.append** – NumPy function used to add values to the end of an array.

## 2) Syntax
```python
np.append(arr, values, axis=None)
```

### Parameters
- `arr` : Original array.
- `values` : Values to append.
- `axis` : Axis along which values are appended.
  - `None` (default): Arrays are flattened before appending.

## 3) Usage
Used to append elements to an existing array. It returns a new array and does not modify the original array.


## Note
- `np.append()` returns a new array.
- The original array remains unchanged.
- When `axis=None`, NumPy flattens the array before appending.

In [28]:
a = np.array([1,2,3,4])

print(np.append(a,10))

[ 1  2  3  4 10]


In [26]:
arr = np.array([[1, 2],
                [3, 4]])

print(np.append(arr,np.ones((arr.shape[0],1)),axis=1))

[[1. 2. 1.]
 [3. 4. 1.]]


In [27]:
arr = np.array([[1, 2],
                [3, 4]])

result = np.append(arr, [[5, 6]], axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


# np.concatenate

## 1) Name
**np.concatenate** – NumPy function used to join two or more arrays along an existing axis.

## 2) Syntax
```python
np.concatenate((arr1, arr2, ...), axis=0)
```

### Parameters
- `arr1, arr2, ...` : Arrays to join.
- `axis` : Axis along which the arrays are joined.
  - `axis=0` → Join rows (vertical).
  - `axis=1` → Join columns (horizontal).

## 3) Usage
Used to combine multiple arrays into a single array.

## Note
- Arrays must have compatible dimensions.
- For `axis=0`, the number of columns must match.
- For `axis=1`, the number of rows must match.
- Returns a new array; the original arrays are unchanged.

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))

print(result)

[1 2 3 4 5 6]


In [31]:
# Row (axis = 0)
a = np.array([[1, 2],  
              [3, 4]])

b = np.array([[5, 6]])

result = np.concatenate((a, b), axis=0)

print(result)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
#  Col (axis = 1)
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5],
              [6]])

result = np.concatenate((a, b), axis=1)

print(result)

[[1 2 5]
 [3 4 6]]


# np.unique

## 1) Name
**np.unique** – NumPy function used to find the unique (distinct) elements in an array.

## 2) Syntax
```python
np.unique(ar, return_index=False, return_inverse=False,
          return_counts=False, axis=None)
```

### Parameters
- `ar` : Input array.
- `return_index` : Returns indices of unique values.
- `return_inverse` : Returns indices to reconstruct the original array.
- `return_counts` : Returns the count of each unique value.
- `axis` : Find unique values along a specified axis.

## 3) Usage
Used to remove duplicate values and return the sorted unique elements.



## Note
- Returns unique values in sorted order.
- Removes duplicate elements automatically.
- Can also return counts, indices, and inverse mappings.

In [33]:
arr = np.array([1, 2, 2, 3, 3, 3, 4])

result = np.unique(arr)

print(result)

[1 2 3 4]


In [35]:
arr = np.array([1, 2, 2, 3, 3, 3, 4,3])

unique_values, counts = np.unique(arr, return_counts=True)

print(unique_values)
print(counts)

[1 2 3 4]
[1 2 4 1]


In [36]:
arr = np.array([[1, 2],
                [1, 2],
                [3, 4]])

result = np.unique(arr, axis=0)

print(result)

[[1 2]
 [3 4]]


# np.expand_dims

## 1) Name
**np.expand_dims** – NumPy function used to add a new axis (dimension) to an array.

## 2) Syntax
```python
np.expand_dims(a, axis)
```

### Parameters
- `a` : Input array.
- `axis` : Position where new axis is inserted.

## 3) Usage
Used to increase the dimensions of an array without changing its data.



## Note
- It does NOT change data, only shape.
- Useful in machine learning for adjusting input dimensions.
- Similar to using `None` or `np.newaxis`.

In [38]:
arr = np.array([1, 2, 3])

result = np.expand_dims(arr, axis=0)

print(result)

[[1 2 3]]


In [39]:
arr = np.array([[1, 2],
                [3, 4]])

result = np.expand_dims(arr, axis=0)

print(result)

[[[1 2]
  [3 4]]]


In [40]:
arr = np.array([1, 2, 3])

result = np.expand_dims(arr, axis=1)

print(result)

[[1]
 [2]
 [3]]


# np.where

## 1) Name
**np.where** – NumPy function used to find indices based on a condition or to choose values conditionally.

---

## 2) Syntax

### Case 1: Condition only
```python
np.where(condition)
```

### Case 2: Choose between two values
```python
np.where(condition, x, y)
```

### Parameters
- `condition` : Condition to check (True/False).
- `x` : Value used where condition is True.
- `y` : Value used where condition is False.

---

## 3) Usage
Used for:
- Finding positions of elements that satisfy a condition
- Conditional replacement in arrays



## Note
- Returns indices when only condition is given.
- Works like a vectorized `if-else`.
- Very useful for fast filtering and data transformation.

In [41]:
arr = np.array([10, 20, 30, 40, 50])

result = np.where(arr > 25)

print(result)

(array([2, 3, 4], dtype=int64),)


In [42]:
arr = np.array([10, 20, 30, 40])

result = np.where(arr > 25, "High", "Low")

print(result)

['Low' 'Low' 'High' 'High']


In [43]:
arr = np.array([1, 2, 3, 4, 5])

result = np.where(arr % 2 == 0, 0, 1)

print(result)

[1 0 1 0 1]


# np.argmax

## 1) Name
**np.argmax** – NumPy function used to find the index of the maximum value in an array.

---

## 2) Syntax
```python
np.argmax(a, axis=None)
```

### Parameters
- `a` : Input array.
- `axis` : Axis along which to find the index of the maximum value.
  - `None` (default): works on flattened array.
  - `0` : column-wise
  - `1` : row-wise

---

## 3) Usage
Used to find the position (index) of the largest element in an array.


## Note
- Returns the **index**, not the value.
- If multiple max values exist, it returns the first occurrence.
- Very useful in machine learning for prediction classes.

In [44]:
arr = np.array([10, 50, 30, 90, 20])

result = np.argmax(arr)

print(result)

3


In [45]:
arr = np.array([[1, 5, 2],
                [9, 3, 7]])

result = np.argmax(arr)

print(result)

3


In [46]:
# col-wise
arr = np.array([[1, 5, 2],
                [9, 3, 7]])

result = np.argmax(arr, axis=0)

print(result)

[1 0 1]


In [47]:
# row-wise
arr = np.array([[1, 5, 2],
                [9, 3, 7]])

result = np.argmax(arr, axis=1)

print(result)

[1 0]


# np.argmin

## 1) Name
**np.argmin** – NumPy function used to find the index of the minimum value in an array.

---

## 2) Syntax
```python
np.argmin(a, axis=None)
```

### Parameters
- `a` : Input array.
- `axis` : Axis along which to find the index of the minimum value.
  - `None` (default): Works on flattened array.
  - `0` : column-wise
  - `1` : row-wise

---

## 3) Usage
Used to get the position (index) of the smallest element in an array.

---



## Note
- Returns the **index**, not the value.
- If multiple minimum values exist, returns the first occurrence.
- Very useful for optimization and ML tasks.

In [48]:
arr = np.array([10, 50, 30, 5, 20])

result = np.argmin(arr)

print(result)

3


In [49]:
arr = np.array([[8, 2, 9],
                [4, 1, 7]])

result = np.argmin(arr)

print(result)

4


In [50]:
# col-wise
arr = np.array([[8, 2, 9],
                [4, 1, 7]])

result = np.argmin(arr, axis=0)

print(result)

[1 1 1]


In [51]:
# row-wise
arr = np.array([[8, 2, 9],
                [4, 1, 7]])

result = np.argmin(arr, axis=1)

print(result)

[1 1]


# np.cumsum

## 1) Name
**np.cumsum** – NumPy function used to compute the cumulative sum of array elements.

---

## 2) Syntax
```python
np.cumsum(a, axis=None, dtype=None)
```

### Parameters
- `a` : Input array.
- `axis` : Axis along which cumulative sum is computed.
  - `None` (default): Works on flattened array.
  - `0` : column-wise
  - `1` : row-wise
- `dtype` : Data type of the output array.

---

## 3) Usage
Used to calculate running totals (cumulative addition) of elements in an array.


## Note
- Produces a running total of elements.
- Very useful in statistics, finance (profit tracking), and data analysis.
- Works differently depending on the axis used.

In [52]:
arr = np.array([1, 2, 3, 4, 5])

result = np.cumsum(arr)

print(result)

[ 1  3  6 10 15]


In [54]:
# Flattened
arr = np.array([[1, 2],
                [3, 4]])

result = np.cumsum(arr)

print(result)

[ 1  3  6 10]


In [55]:
# col-wise
arr = np.array([[1, 2],
                [3, 4]])

result = np.cumsum(arr, axis=0)

print(result)

[[1 2]
 [4 6]]


In [56]:
# row-wise
arr = np.array([[1, 2],
                [3, 4]])

result = np.cumsum(arr, axis=1)

print(result)

[[1 3]
 [3 7]]


# np.cumprod

## 1) Name
**np.cumprod** – NumPy function used to compute the cumulative product of array elements.

---

## 2) Syntax
```python
np.cumprod(a, axis=None, dtype=None)
```

### Parameters
- `a` : Input array.
- `axis` : Axis along which cumulative product is computed.
  - `None` (default): Works on flattened array.
  - `0` : column-wise
  - `1` : row-wise
- `dtype` : Data type of the output array.

---

## 3) Usage
Used to calculate running multiplication (cumulative product) of elements in an array.

## Note
- Produces a running multiplication of elements.
- Very useful in probability, finance, and sequential growth calculations.
- Output shape depends on axis used.

In [57]:
arr = np.array([1, 2, 3, 4])

result = np.cumprod(arr)

print(result)

[ 1  2  6 24]


In [58]:
arr = np.array([[1, 2],
                [3, 4]])

result = np.cumprod(arr)

print(result)

[ 1  2  6 24]


In [60]:
# col-wise
arr = np.array([[1, 2],
                [3, 4]])

result = np.cumprod(arr, axis=0)

print(result)

[[1 2]
 [3 8]]


In [61]:
# row-wise
arr = np.array([[1, 2],
                [3, 4]])

result = np.cumprod(arr, axis=1)

print(result)

[[ 1  2]
 [ 3 12]]


# np.percentile

## 1) Name
**np.percentile** – NumPy function used to compute the value below which a given percentage of data falls.

---

## 2) Syntax
```python
np.percentile(a, q, axis=None, interpolation='linear')
```

### Parameters
- `a` : Input array.
- `q` : Percentile or sequence of percentiles (0–100).
- `axis` : Axis along which percentile is computed.
  - `None` (default): Works on flattened array.
- `interpolation` : Method used when percentile lies between data points (new NumPy uses `method` instead).

---

## 3) Usage
Used in statistics to understand data distribution (e.g., median, quartiles, spread).


## Note
- Percentile shows **relative position in data**.
- 50th percentile = median.
- 25th = Q1, 75th = Q3.
- Very useful in statistics, data analysis, and ML preprocessing.

In [63]:
arr = np.array([10, 20, 30, 40, 50])

result = np.percentile(arr, 50)

print(result)

30.0


In [64]:

arr = np.array([10, 20, 30, 40, 50])

result = np.percentile(arr, [25, 50, 75])

print(result)

[20. 30. 40.]


In [65]:
arr = np.array([[1, 2],
                [3, 4]])

result = np.percentile(arr, 50)

print(result)

2.5


In [66]:
# Axis-wise
arr = np.array([[1, 2],
                [3, 4]])

result = np.percentile(arr, 50, axis=0)

print(result)

[2. 3.]


# np.histogram

## 1) Name
**np.histogram** – NumPy function used to compute the frequency distribution of data (how many values fall into each range/bin).

---

## 2) Syntax
```python
np.histogram(a, bins=10, range=None, density=False)
```

### Parameters
- `a` : Input array (data values).
- `bins` : Number of equal-width intervals (or custom bin edges).
- `range` : Lower and upper range of bins.
- `density` : If True, returns probability density instead of counts.

---

## 3) Usage
Used to analyze data distribution by dividing data into intervals (bins) and counting how many values fall in each bin.

## Note
- First output → frequency counts  
- Second output → bin edges  
- Useful for data visualization and statistics  
- Often used with `matplotlib.pyplot.hist()` for plotting

In [67]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 5])

result = np.histogram(arr, bins=4)

print(result)

(array([1, 2, 3, 2], dtype=int64), array([1., 2., 3., 4., 5.]))


In [68]:
arr = np.array([10, 20, 30, 40, 50, 60])

result = np.histogram(arr, bins=[0, 25, 50, 75])

print(result)

(array([2, 2, 2], dtype=int64), array([ 0, 25, 50, 75]))


In [69]:
arr = np.array([1, 2, 3, 4, 5])

result = np.histogram(arr, bins=5, density=True)

print(result)

(array([0.25, 0.25, 0.25, 0.25, 0.25]), array([1. , 1.8, 2.6, 3.4, 4.2, 5. ]))


# np.corrcoef

## 1) Name
**np.corrcoef** – NumPy function used to compute the correlation coefficient between variables.

---

## 2) Syntax
```python
np.corrcoef(x, y=None, rowvar=True)
```

### Parameters
- `x` : Input array(s).
- `y` : Optional second variable.
- `rowvar` :
  - `True` (default): each row is a variable.
  - `False`: each column is a variable.

---

## 3) Usage
Used to measure the **relationship (correlation)** between two or more variables.
- Value ranges from **-1 to +1**
  - `+1` → perfect positive correlation  
  - `0` → no correlation  
  - `-1` → perfect negative correlation  



## Note
- Produces a **correlation matrix**.
- Helps in statistics, data analysis, and machine learning.
- Shows strength and direction of linear relationships.

In [70]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

result = np.corrcoef(x, y)

print(result)

[[1. 1.]
 [1. 1.]]


In [71]:
data = np.array([
    [1, 2, 3, 4, 5],
    [2, 4, 6, 8, 10],
    [5, 4, 3, 2, 1]
])

result = np.corrcoef(data)

print(result)

[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]]


In [72]:
data = np.array([
    [1, 2, 3, 4, 5],
    [2, 4, 6, 8, 10],
    [5, 4, 3, 2, 1]
])

result = np.corrcoef(data)

print(result)

[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]]


# np.isin

## 1) Name
**np.isin** – NumPy function used to check whether elements of one array exist in another array.

---

## 2) Syntax
```python
np.isin(element, test_elements, assume_unique=False, invert=False)
```

### Parameters
- `element` : Input array to check.
- `test_elements` : Values to compare against.
- `assume_unique` : If True, speeds up processing (assumes inputs are unique).
- `invert` : If True, returns elements NOT in `test_elements`.

---

## 3) Usage
Used to perform **membership testing** (like `in` keyword, but for arrays).



## Note
- Returns a **boolean array**.
- Very useful for filtering data.
- Similar to SQL `IN` condition or Python `in`, but works on full arrays efficiently.

In [73]:
arr = np.array([1, 2, 3, 4, 5])

result = np.isin(arr, [2, 4, 6])

print(result)

[False  True False  True False]


In [74]:
arr = np.array([10, 20, 30, 40, 50])

result = arr[np.isin(arr, [20, 50])]

print(result)

[20 50]


In [75]:
arr = np.array([1, 2, 3, 4, 5])

result = np.isin(arr, [2, 4], invert=True)

print(result)

[ True False  True False  True]


# np.flip

## 1) Name
**np.flip** – NumPy function used to reverse the order of elements in an array along a specified axis.

---

## 2) Syntax
```python
np.flip(m, axis=None)
```

### Parameters
- `m` : Input array.
- `axis` : Axis along which to flip the array.
  - `None` (default): Flips the array in all dimensions (completely reversed).
  - `0` : Flip rows (up-down).
  - `1` : Flip columns (left-right).

---

## 3) Usage
Used to reverse elements of an array, similar to mirroring or reversing order.

## Note
- Does not change original array.
- Useful for reversing data, images, and sequences.
- Works on any dimensional array.

In [76]:
arr = np.array([1, 2, 3, 4, 5])

result = np.flip(arr)

print(result)

[5 4 3 2 1]


In [77]:
arr = np.array([[1, 2],
                [3, 4]])

result = np.flip(arr)

print(result)

[[4 3]
 [2 1]]


In [78]:
# Row
arr = np.array([[1, 2],
                [3, 4]])

result = np.flip(arr, axis=0)

print(result)

[[3 4]
 [1 2]]


In [79]:
# Col
arr = np.array([[1, 2],
                [3, 4]])

result = np.flip(arr, axis=1)

print(result)

[[2 1]
 [4 3]]


# np.put

## 1) Name
**np.put** – NumPy function used to change specific elements of an array by index.

---

## 2) Syntax
```python
np.put(a, ind, v, mode='raise')
```

### Parameters
- `a` : Input array (modified in-place).
- `ind` : Index or list of indices where values should be placed.
- `v` : Values to insert (can repeat if needed).
- `mode` :
  - `'raise'` → error if index is out of bounds (default)
  - `'wrap'` → wraps around
  - `'clip'` → clips to valid range

---

## 3) Usage
Used to directly update values in an array at specific positions using index numbers.

⚠️ Important: It modifies the original array (in-place).

## Note
- Works using **flattened index order**.
- Directly modifies original array.
- Faster alternative for bulk index assignment compared to loops.

In [80]:
arr = np.array([10, 20, 30, 40, 50])

np.put(arr, [1, 3], [99, 88])

print(arr)

[10 99 30 88 50]


In [81]:
arr = np.array([1, 2, 3, 4, 5])

np.put(arr, [0, 2, 4], 100)

print(arr)

[100   2 100   4 100]


In [82]:
arr = np.array([[1, 2],
                [3, 4]])

np.put(arr, [0, 3], [9, 8])

print(arr)

[[9 2]
 [3 8]]


# np.delete

## 1) Name
**np.delete** – NumPy function used to delete elements from an array at specified indices.

---

## 2) Syntax
```python
np.delete(arr, obj, axis=None)
```

### Parameters
- `arr` : Input array.
- `obj` : Index or list of indices to delete.
- `axis` :
  - `None` (default): array is flattened before deletion.
  - `0` : delete rows (in 2D)
  - `1` : delete columns (in 2D)

---

## 3) Usage
Used to remove elements, rows, or columns from a NumPy array.  
⚠️ It does **not modify the original array**, it returns a new array.

## Note
- Returns a **new array** (original remains unchanged).
- Without `axis`, array is flattened first.
- Very useful for data cleaning and preprocessing.

In [83]:
arr = np.array([10, 20, 30, 40, 50])

result = np.delete(arr, [1, 3])

print(result)

[10 30 50]


In [84]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

result = np.delete(arr, 1, axis=0)

print(result)

[[1 2]
 [5 6]]


In [85]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.delete(arr, 1, axis=1)

print(result)

[[1 3]
 [4 6]]


# Set Operations

# np.union1d

## 1) Name
**np.union1d** – NumPy function used to find the union (all unique elements) of two arrays.

---

## 2) Syntax
```python
np.union1d(ar1, ar2)
```

### Parameters
- `ar1` : First input array.
- `ar2` : Second input array.

---

## 3) Usage
Used to combine two arrays and return **sorted unique values** from both.


## Note
- Returns **unique sorted values**.
- Removes duplicates automatically.
- Similar to mathematical set union.
- Very useful in data analysis and set operations.

In [86]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

result = np.union1d(a, b)

print(result)

[1 2 3 4 5 6]


In [87]:
a = np.array([1, 1, 2, 3])
b = np.array([3, 4, 4, 5])

result = np.union1d(a, b)

print(result)

[1 2 3 4 5]


In [88]:
a = np.array([10, 20, 30])
b = np.array([5, 10, 15])

result = np.union1d(a, b)

print(result)

[ 5 10 15 20 30]


# np.intersect1d

## 1) Name
**np.intersect1d** – NumPy function used to find common elements between two arrays.

---

## 2) Syntax
```python
np.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
```

### Parameters
- `ar1` : First input array.
- `ar2` : Second input array.
- `assume_unique` : If True, assumes inputs are already unique (faster).
- `return_indices` : If True, returns indices of intersection elements.

---

## 3) Usage
Used to get **common elements** (intersection) between two arrays.


## Note
- Returns **sorted unique common elements**.
- Works like set intersection in mathematics.
- Very useful in data matching and filtering tasks.

In [89]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

result = np.intersect1d(a, b)

print(result)

[3 4]


In [90]:
a = np.array([1, 2, 2, 3, 4])
b = np.array([2, 4, 4, 6])

result = np.intersect1d(a, b)

print(result)

[2 4]


In [101]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([20, 40, 60])

result, idx_a, idx_b = np.intersect1d(a, b, return_indices=True)

print(result)
print(idx_a)
print(idx_b)

[20 40]
[1 3]
[0 1]


# np.setdiff1d

## 1) Name
**np.setdiff1d** – NumPy function used to find elements that are in one array but not in another.

---

## 2) Syntax
```python
np.setdiff1d(ar1, ar2, assume_unique=False)
```

### Parameters
- `ar1` : First input array (main array).
- `ar2` : Second input array (elements to exclude).
- `assume_unique` : If True, assumes inputs are unique (faster).

---

## 3) Usage
Used to get **difference between two arrays**:
👉 “elements in `ar1` that are NOT in `ar2`”


## Note
- Returns **sorted unique values**.
- Removes all elements of `ar2` from `ar1`.
- Similar to set difference in mathematics:
  - `A - B`

In [92]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 5])

result = np.setdiff1d(a, b)

print(result)

[1 2 4]


In [93]:
a = np.array([1, 2, 2, 3, 4, 5])
b = np.array([2, 5])

result = np.setdiff1d(a, b)

print(result)

[1 3 4]


In [94]:
a = np.array([10, 20, 30, 40])
b = np.array([20, 50])

result = np.setdiff1d(a, b)

print(result)

[10 30 40]


# np.setxor1d

## 1) Name
**np.setxor1d** – NumPy function used to find elements that are in either of the two arrays, but not in both.

---

## 2) Syntax
```python
np.setxor1d(ar1, ar2, assume_unique=False)
```

### Parameters
- `ar1` : First input array.
- `ar2` : Second input array.
- `assume_unique` : If True, assumes inputs are unique (faster computation).

---

## 3) Usage
Used to get **symmetric difference** between two arrays:
👉 Elements that are **only in one array, not in both**.

## Note
- Returns **sorted unique values**.
- Removes elements common to both arrays.
- Equivalent to:
  - `(A ∪ B) - (A ∩ B)`
- Very useful in set-based data comparisons.

In [95]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

result = np.setxor1d(a, b)

print(result)

[1 2 5 6]


In [96]:
a = np.array([1, 2, 2, 3])
b = np.array([2, 3, 4])

result = np.setxor1d(a, b)

print(result)

[1 4]


In [97]:
a = np.array([10, 20, 30])
b = np.array([20, 40, 50])

result = np.setxor1d(a, b)

print(result)

[10 30 40 50]


# np.in1d

## 1) Name
**np.in1d** – NumPy function used to check whether elements of one array are present in another array.

---

## 2) Syntax
```python
np.in1d(ar1, ar2, assume_unique=False, invert=False)
```

### Parameters
- `ar1` : Input array to test.
- `ar2` : Values to check against.
- `assume_unique` : If True, assumes inputs are unique (faster).
- `invert` : If True, returns elements NOT in `ar2`.

---

## 3) Usage
Used for **membership testing** (like `np.isin`, but older version):
👉 Checks which elements of `ar1` exist in `ar2`.


## Note
- Returns a **boolean 1D array**.
- Similar to `np.isin`, but `np.isin` is preferred in modern NumPy.
- Useful for filtering and membership checks.

In [98]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6])

result = np.in1d(a, b)

print(result)

[False  True False  True False]


In [99]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([20, 50])

result = a[np.in1d(a, b)]

print(result)

[20 50]


In [100]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4])

result = np.in1d(a, b, invert=True)

print(result)

[ True False  True False  True]


# np.clip()

## 1) Name
**np.clip** – NumPy function used to limit (restrict) values in an array within a specified range.

---

## 2) Syntax
```python
np.clip(a, a_min, a_max)
```

### Parameters
- `a` : Input array.
- `a_min` : Minimum allowed value.
- `a_max` : Maximum allowed value.

---

## 3) Usage
Used to **bound values** so they do not go below or above a given range.

👉 Values smaller than `a_min` become `a_min`  
👉 Values greater than `a_max` become `a_max`


## Note
- Very useful in **image processing** (pixel range 0–255).
- Also used in ML to prevent extreme values.
- Does not change array shape, only values.

In [102]:
arr = np.array([1, 5, 10, 15, 20])

result = np.clip(arr, 5, 15)

print(result)

[ 5  5 10 15 15]


In [103]:
arr = np.array([-10, -5, 0, 5, 10])

result = np.clip(arr, 0, 8)

print(result)

[0 0 0 5 8]


In [104]:
arr = np.array([50, 120, 200, 300])

result = np.clip(arr, 0, 255)

print(result)

[ 50 120 200 255]


# Other Functions

# 1) np.allclose

## Name
**np.allclose** – checks whether two arrays are approximately equal element-wise.

## Syntax
```python
np.allclose(a, b, rtol=1e-05, atol=1e-08)
```

## Usage
Used for comparing floating-point arrays (handles small rounding errors).

## Example
```python
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.0, 3.0000001])

print(np.allclose(a, b))
```

## Output
```python
True
```

---

# 2) np.equal (==)

## Name
**np.equal** – checks exact equality element-wise.

## Syntax
```python
np.equal(a, b)
# or
a == b
```

## Usage
Used when values must match exactly.

## Example
```python
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])

print(a == b)
```

## Output
```python
[ True  True False]
```

---

# 3) np.repeat

## Name
**np.repeat** – repeats elements of an array.

## Syntax
```python
np.repeat(a, repeats, axis=None)
```

## Usage
Used to duplicate elements multiple times.

## Example
```python
import numpy as np

arr = np.array([1, 2, 3])

print(np.repeat(arr, 2))
```

## Output
```python
[1 1 2 2 3 3]
```

---

# 4) np.tile (you wrote np.title)

## Name
**np.tile** – repeats the entire array in a pattern.

## Syntax
```python
np.tile(a, reps)
```

## Usage
Used to create repeated blocks of an array.

## Example
```python
import numpy as np

arr = np.array([1, 2])

print(np.tile(arr, 3))
```

## Output
```python
[1 2 1 2 1 2]
```

---

# 5) np.count_nonzero (you wrote np.count_zero)

## Name
**np.count_nonzero** – counts non-zero elements.

## Syntax
```python
np.count_nonzero(a)
```

## Usage
Used to count how many values are NOT zero.

## Example
```python
import numpy as np

arr = np.array([0, 1, 2, 0, 3])

print(np.count_nonzero(arr))
```

## Output
```python
3
```

---

# 6) np.random.uniform (you wrote np.uniform)

## Name
**np.random.uniform** – generates random numbers in a range.

## Syntax
```python
np.random.uniform(low, high, size)
```

## Usage
Used to generate random floating-point numbers.

## Example
```python
import numpy as np

print(np.random.uniform(0, 1, 5))
```

## Output (example)
```python
[0.12 0.88 0.45 0.67 0.03]
```

---

# 7) np.swapaxes

## Name
**np.swapaxes** – swaps two axes of an array.

## Syntax
```python
np.swapaxes(a, axis1, axis2)
```

## Usage
Used to rearrange dimensions of arrays.

## Example
```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.swapaxes(arr, 0, 1))
```

## Output
```python
[[1 4]
 [2 5]
 [3 6]]
```

---

# Summary
- `allclose` → approximate comparison  
- `equal` → exact comparison  
- `repeat` → repeat elements  
- `tile` → repeat full array pattern  
- `count_nonzero` → count non-zero values  
- `random.uniform` → random float values  
- `swapaxes` → change array dimensions  